version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ingicat_db
      POSTGRES_USER: fabian
      POSTGRES_PASSWORD: ingicat*1003
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=ingicat_db
      - DB_USER=fabian
      - DB_PASSWORD=ingicat*1003
      - DB_HOST=db
      - DB_PORT=5432
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: fabian.fernandez@ingicat.com
      PGADMIN_DEFAULT_PASSWORD: fabian1003
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  

volumes:
  postgres_data:
  pgadmin_data:
  ollama_data:


