# Generated by Django 5.1.7 on 2025-03-25 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proyecto', models.CharField(choices=[('PREDIOS PROPIOS', 'PREDIOS PROPIOS'), ('SERVIDUMBRES', 'SERVIDUMBRES')], max_length=16)),
                ('vigencia', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4)),
                ('gerencia', models.CharField(choices=[('VAO', 'VAO'), ('GPA', 'GPA'), ('VRC', 'VRC'), ('GCT', 'GCT'), ('GMA', 'GMA'), ('GRI', 'GRI'), ('GTA', 'GTA'), ('VRO', 'VRO'), ('GCH', 'GCH'), ('GDA', 'GDA'), ('GDT', 'GDT'), ('VPI', 'VPI'), ('VFS', 'VFS')], max_length=4)),
                ('categoria_predio_fmi', models.CharField(choices=[('COLINDANTE', 'COLINDANTE'), ('FOLIO ESTUDIO', 'FOLIO ESTUDIO'), ('MATRIZ', 'MATRIZ'), ('MATRIZ_COLINDANTE', 'MATRIZ_COLINDANTE'), ('PROPIO', 'PROPIO'), ('SEGREGADO', 'SEGREGADO'), ('SIN INFORMACIÓN', 'SIN INFORMACIÓN')], max_length=100)),
                ('estado_folio_matricula', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('CERRADO', 'CERRADO'), ('SIN INFORMACIÓN', 'SIN INFORMACIÓN')], max_length=100)),
                ('categoria_fmi', models.CharField(choices=[('ADICIONALES', 'ADICIONALES'), ('COMPLEMENTACIÓN', 'COMPLEMENTACIÓN'), ('SIN INFORMACIÓN', 'SIN INFORMACIÓN'), ('TRADICIÓN', 'TRADICIÓN')], max_length=50)),
                ('tipo_documental', models.CharField(choices=[('ACTA', 'ACTA'), ('ACTO ADMINISTRATIVO', 'ACTO ADMINISTRATIVO'), ('AUTO', 'AUTO'), ('CERTIFICADO', 'CERTIFICADO'), ('DECLARACIÓN', 'DECLARACIÓN'), ('DECRETO', 'DECRETO'), ('DEMANDA', 'DEMANDA'), ('DOCUMENTO', 'DOCUMENTO'), ('ESCRITURA', 'ESCRITURA'), ('EXPEDIENTE', 'EXPEDIENTE'), ('RESOLUCIÓN', 'RESOLUCIÓN'), ('SENTENCIA', 'SENTENCIA')], max_length=50)),
                ('estado', models.CharField(choices=[('CARGADO A OTRO PREDIO', 'CARGADO A OTRO PREDIO'), ('CARGADO EN EL PREDIO', 'CARGADO EN EL PREDIO'), ('CARGADO EN SHAREPOINT', 'CARGADO EN SHAREPOINT'), ('NO ENCONTRADO', 'NO ENCONTRADO'), ('NO REQUIERE', 'NO REQUIERE'), ('PENDIENTE VERIFICAR', 'PENDIENTE VERIFICAR'), ('SERVIDOR INGICAT', 'SERVIDOR INGICAT')], max_length=50)),
                ('estado_compra', models.CharField(choices=[('ADQUIRIDO', 'ADQUIRIDO'), ('NO REQUIERE', 'NO REQUIERE'), ('PENDIENTE POR SOLICITAR', 'PENDIENTE POR SOLICITAR'), ('PENDIENTE VERIFICAR', 'PENDIENTE VERIFICAR'), ('SOLICITADO', 'SOLICITADO')], max_length=50)),
                ('sub_estado_compra', models.CharField(choices=[('ADQUIRIDO PREDIO PROPIOS', 'ADQUIRIDO PREDIO PROPIOS'), ('ADQUIRIDO SERVIDUMBRES', 'ADQUIRIDO SERVIDUMBRES'), ('ERROR REGISTRAL', 'ERROR REGISTRAL'), ('NO APLICA', 'NO APLICA'), ('SOLICITADO / CERTIFICADO NO EXISTE', 'SOLICITADO / CERTIFICADO NO EXISTE'), ('SOLICITADO PREDIO PROPIOS', 'SOLICITADO PREDIO PROPIOS'), ('SOLICITADO SERVIDUMBRES', 'SOLICITADO SERVIDUMBRES')], max_length=50)),
                ('envio_open_text', models.CharField(choices=[('NO', 'NO'), ('NO APLICA', 'NO APLICA'), ('NO REQUIERE', 'NO REQUIERE'), ('PENDIENTE', 'PENDIENTE'), ('SI', 'SI'), ('YA ESTA', 'YA ESTA')], max_length=50)),
                ('accion_tecnica', models.CharField(choices=[('ALIMENTAR EXPEDIENTE PREDIAL', 'ALIMENTAR EXPEDIENTE PREDIAL'), ('ALIMENTAR PREDIO GESTIÓN', 'ALIMENTAR PREDIO GESTIÓN'), ('ALIMENTAR PREDIO MATRIZ', 'ALIMENTAR PREDIO MATRIZ'), ('CARPETA CERO', 'CARPETA CERO'), ('CREAR EXPEDIENTE', 'CREAR EXPEDIENTE'), ('NO REQUIERE', 'NO REQUIERE')], max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
