# Generated by Django 5.1.7 on 2025-03-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_predio'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
