# Generated by Django 5.1.7 on 2025-03-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_predio_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True),
        ),
    ]
