# Generated by Django 5.1.7 on 2025-03-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_predio_fecha_respuesta_predio_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='es_importante',
            field=models.BooleanField(default=False),
        ),
    ]
