# Generated by Django 5.1.7 on 2025-04-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_predio_es_importante'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='fecha_diferencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='ultima_fecha_acceso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
