# Generated by Django 5.1.7 on 2025-04-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_predio_fecha_diferencia_predio_ultima_fecha_acceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='fecha_diferencia',
        ),
    ]
