# Generated by Django 5.1.7 on 2025-04-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_remove_predio_fecha_diferencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predio',
            options={'ordering': ['-fecha_solicitud']},
        ),
        migrations.AddField(
            model_name='predio',
            name='campo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='ced_catastral',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='cod_sig',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='documento',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='entidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='fecha_reiteracion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='fmi',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='predio',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='nom_predio',
            field=models.CharField(default='Sin Informacion', max_length=50),
        ),
    ]
