# Generated by Django 5.1.7 on 2025-04-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_predio_options_predio_campo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='adquirir',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='cod_especificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='cod_sig_asociado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='cod_sig_opentext',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='documentos_municipio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='estrategia',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('APOYO FISICO', 'APOYO FISICO'), ('NO APLICA', 'NO APLICA')], default='NO APLICA', max_length=50),
        ),
        migrations.AddField(
            model_name='predio',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='fecha_nueva_busqueda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='link_sharepoint',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='nombre_predio_opentext',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='paquete',
            field=models.CharField(choices=[('PAQUETE 4', 'PAQUETE 4'), ('PAQUETE 6', 'PAQUETE 6'), ('SIN PAQUETE', 'SIN PAQUETE')], default='PAQUETE 4', max_length=30),
        ),
        migrations.AddField(
            model_name='predio',
            name='repetido',
            field=models.CharField(choices=[('REPETIDO', 'REPETIDO'), ('UNICO', 'UNICO'), ('REPETIDO ADQUIRIR', 'REPETIDO ADQUIRIR'), ('NO APLICA', 'NO APLICA')], default='NO APLICA', max_length=50),
        ),
        migrations.AddField(
            model_name='predio',
            name='responsable_adquisicion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='responsable_nueva_busqueda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='responsable_seguimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
